import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { LightDarkSwitch } from "./components/LightDarkSwitch";
import ProfileMenu from "./components/ProfileMenu";
import { SignInButton } from "./components/SignInButton";
import { ThemeProvider } from "./components/theme-provider";
import "./globals.css";
import { auth } from "./src/lib/auth";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased m-5 ", fontSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="flex justify-between ">
            <h1 className="text-2xl font-bold">Diet Tracker</h1>

            <div className="flex gap-4">
              {!session ? <SignInButton /> : <ProfileMenu user={session.user} expires={session.expires} />}

              <LightDarkSwitch />
            </div>
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
